## importing numpy 

In [1]:
import numpy as np

### continuing array generated functions

#### using np.fromiter() : Create a new 1-dimensional array from an iterable object(example : range())

In [4]:
# creating a iterable 
iterable = (i**2 for i in range(5))
# creating array from iterable 
arr = np.fromiter(iterable,dtype=int)
# printing the array 
print(arr)
# printing the type of array 
print(type(arr))
# printing the dimensions of arr
dimension = arr.ndim
print(dimension)

[ 0  1  4  9 16]
<class 'numpy.ndarray'>
1


In [5]:
# creating 2 D array from iter

In [26]:
# creating a iterable 
iterable = ((x+1, x+2,x+3) for x in range(5))
# printing the iterable object 
print(iterable)
# creating 2D array from iterable 
arr = np.fromiter(iterable,dtype=(int,3))
# printing the array 
print(arr)
# printing the type of array 
print(type(arr))
# printing the dimensions of arr
dimension = arr.ndim
print(dimension)

<generator object <genexpr> at 0x7f8e8e91e3c0>
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
<class 'numpy.ndarray'>
2


#### using np.fromstring() : this will use to generate an array from string by passing the sep

In [29]:
# creating a string 
string = '1,2,3,4,5'
# creating array of int type using string 
arr = np.fromstring(string,dtype=int,sep=',')
# printing the array and it's dimensions
dimension = arr.ndim
print(arr)
print(dimension)

[1 2 3 4 5]
1


#### using np.arange()

##### range() is not able to give float values between to floating point number to overcome this we used np.arange(start,end,stepsize) 

In [32]:
# creating an array using np.arange()
arr = np.arange(0,9,0.2)
# printing the array 
print(arr)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8]


#### Note:  it includes start but does not include end 

#### using np.linspace(start,end,no.of values you want between start and end)

In [37]:
# creating an array using np.linspace
arr = np.linspace(3,11,10)
# printing the array 
print(arr)

[ 3.          3.88888889  4.77777778  5.66666667  6.55555556  7.44444444
  8.33333333  9.22222222 10.11111111 11.        ]


#### using np.logspace(start,end,no.of values you want, logbase)

In [39]:
# creating array usin np.logspace()
arr = np.logspace(1,11,20,base =2)
# printing the arr
print(arr)

[2.00000000e+00 2.88049308e+00 4.14862018e+00 5.97503585e+00
 8.60552469e+00 1.23940771e+01 1.78505267e+01 2.57091593e+01
 3.70275276e+01 5.33287684e+01 7.68065741e+01 1.10620402e+02
 1.59320651e+02 2.29461017e+02 3.30480435e+02 4.75973302e+02
 6.85518900e+02 9.87316222e+02 1.42197877e+03 2.04800000e+03]


#### using np.zeros(shape)

In [41]:
# creating an array using np.zeros()
arr = np.zeros((3,3),dtype=int)
# printing the array 
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### np.ones(shape)

In [42]:
# creating the array using np.ones
arr = np.ones((4,4),dtype=int)
# printing the array 
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Arithmatic Operations on array with single integer or floating point number 

#### Addition

In [43]:
# creating an array 
arr = np.ones((3,3),dtype=int)
# performing addition
new_arr = arr+5
# printing the new array
print(new_arr)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [44]:
#### Subtraction

In [47]:
# creating an array 
arr = np.ones((3,3),dtype=int)
# performing addition
new_arr = arr+5
# printing the new array
print(new_arr)

# performing subtraction on new_arr
newarr = new_arr-3
# printing the result
print('\n Here is the result of Subtraction : \n')
print(newarr)

[[6 6 6]
 [6 6 6]
 [6 6 6]]

 Here is the result of Subtraction : 

[[3 3 3]
 [3 3 3]
 [3 3 3]]


Note : Same for Divison , modulus, multiplication 