## Numpy Basics

##### Numpy stands for Numerical Python 
##### Numpy performs fastest mathematical calculations because it is built on C++ and as we know C++ is the fastest language known till now
##### Another main reason for it's Fastest calculation is because of it's basics property of array and array uses vectorization 

## Import Statement for numpy 

In [1]:
import numpy as np 

## Version Checking in Numpy

In [2]:
np.__version__

'1.24.3'

## Documentation Checking in Numpym

In [3]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

## Creating an array using python Data Structures in Numpy 

#### using lists

In [5]:
# creating a python lists
l = [1,2,3,4,5]
# converting list into an array using np.array() method of numpy
arr = np.array(l)
# checking the dimension of an array 
dimension = arr.ndim

# printing the array and it's dimensions

print(arr)
print(type(arr))  # printing the type to know the conversion is successfull or not
print(dimension)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


#### using tuple

In [6]:
# creating a python tuple
t = (1,2,3,4,5)
# converting tuple into an array using np.array() method of numpy
arr = np.array(t)
# checking the dimension of an array 
dimension = arr.ndim

# printing the array and it's dimensions

print(arr)
print(type(arr))  # printing the type to know the conversion is successfull or not
print(dimension)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


#### using set

In [7]:
# creating a python set
s = {1,2,3,4,5}
# converting set into an array using np.array() method of numpy
arr = np.array(s)
# checking the dimension of an array 
dimension = arr.ndim

# printing the array and it's dimensions

print(arr)
print(type(arr))  # printing the type to know the conversion is successfull or not
print(dimension)

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>
0


## Matrix in Numpy 

#### Matrix is a subclass of an array which is by default in 2D 

### Converting python Data Structures into Matrix 

#### using lists

In [8]:
# creating a list
l = [1,2,3,4,5]
# converting list into matrix using np.matrix() method 
mat = np.matrix(l)
# checking the dimension of mat
dimension = mat.ndim

# printing the converted matrix and dimension
print(mat)
print(dimension)

[[1 2 3 4 5]]
2


#### using tuple

In [9]:
# creating a tuple
t = [1,2,3,4,5]
# converting tuple into matrix using np.matrix() method 
mat = np.matrix(t)
# checking the dimension of mat
dimension = mat.ndim

# printing the converted matrix and dimension
print(mat)
print(dimension)

[[1 2 3 4 5]]
2


#### using set

In [11]:
# creating a set 
s = {1,2,3,4,5}
# converting set into matrix using np.matrix() method 
mat = np.matrix(s)
# checking the dimension of mat
dimension = mat.ndim

# printing the converted matrix and dimension
print(mat)
print(dimension)

[[{1, 2, 3, 4, 5}]]
2


#### Note : you can't pass  a 3 D data collection in np.matrix if you did this it will throw an error because matrix by default in 2 D 

In [12]:
# creating a 3 D lists
l = [[[1,2,3],[3,3,2],[3,32,2]]]
# converting the list into matrix 
mat = np.matrix(l)
# printint the matrix 
print(mat)

ValueError: matrix must be 2-dimensional

## More Ways to convert python Data Structure into numpy array : 

#### np.asarray()
#### np.asanyarray()
#### np.fromfunction()
#### np.fromiter()
#### np.fromstring()
#### np.linspace()
#### np.logspace()

#### np.asrray()

In [17]:
# creating a normal array with default parameters By default, the data-type is inferred from the input data.
arr1 = np.asarray([1,2,3,4])
# creating a array with changing parameter dtype and setting it to int to get all elements of intger type
arr2 = np.asarray([1,2,3,4],dtype=float)
# printing the arrays
print(arr1)
print(arr2)

[1 2 3 4]
[1. 2. 3. 4.]


### np.asanyarray() : it will convert any collection into any array except those which is a subclass of array 

In [23]:
# creating a normal array with default parameters By default, the data-type is inferred from the input data.
arr1 = np.asanyarray([1,2,3,4])
# creating a array with changing parameter dtype and setting it to int to get all elements of intger type
arr2 = np.asanyarray([1,2,3,4],dtype=float)
# printing the arrays
print(arr1,type(arr1))
print(arr2,type(arr2))


# creating a matrix which is a subclass of array 
mat = np.matrix([1,2,3,4])
# passing matrix as a parameter to np.asanyarray()
arr3 = np.asanyarray(mat,dtype = float)
# printing the arr and it's type
print(arr3,type(arr3))

[1 2 3 4] <class 'numpy.ndarray'>
[1. 2. 3. 4.] <class 'numpy.ndarray'>
[[1. 2. 3. 4.]] <class 'numpy.matrix'>


#### np.fromfunction() : Construct an array by executing a function over each coordinate.

In [43]:
# creating an array
arr1 = np.fromfunction(lambda i,j:np.where((i==j),1,0),shape=(2,2))
# creating another array 
arr2 = np.fromfunction(lambda i,j:np.where((i%j==0) & (i!=0) | (j!=0),3,4),shape=(4,4))

# printing the arrays 
print(arr1)
print(arr2)

[[1 0]
 [0 1]]
[[4 3 3 3]
 [4 3 3 3]
 [4 3 3 3]
 [4 3 3 3]]


/tmp/ipykernel_5369/1465332167.py:4: RuntimeWarning: invalid value encountered in remainder
  arr2 = np.fromfunction(lambda i,j:np.where((i%j==0) & (i!=0) | (j!=0),3,4),shape=(4,4))


In [44]:
pwd

'/home/monsters/Documents/Daywise_learning/Date:4-06-2024_Topics: Numpy_basics'

In [ ]:
cd